# Generated by Django 3.2.19 on 2023-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoAnimal', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
